### ISSUE TITLE
sacn: [WARN] sACN: Ignoring malformed sACN universe discovery packet from component XXX

### ISSUE THREAD

**Issue by mxwendler** [ETCLabs/sACN#67]
Hello, can you please have a look at the issue discussed here?
https://github.com/docsteer/sacnview/issues/263
With the best regards and thank you for this awesome library!

**Comment by ChristianReese** [comment]
Hello @mxwendler - thank you for reporting this. A fix has been made and will be integrated in a new 2.0.2 build soon, likely early next week.

**Comment by ChristianReese** [comment]
Issue fixed in 2.0.2.2
