### ISSUE TITLE
When linking statically in windows from an "install" build (not through CMake), there's 2 dependencies missing for EtcPal

### ISSUE THREAD

**Issue by onar3d** [ETCLabs/sACN#68]
I followed the instructions to build and create an "install" with CMake.

My project compiles but fails when linking with the following:

1>EtcPal.lib(os_netint.obj) : error LNK2019: unresolved external symbol __imp_GetBestInterfaceEx referenced in function copy_all_netint_info
1>EtcPal.lib(os_netint.obj) : error LNK2019: unresolved external symbol __imp_GetAdaptersAddresses referenced in function os_enumerate_interfaces

Possibly I'm doing something wrong, but I figured I can still ask here in case you can help me with the above.

I'm building with visual studio 2022, pointing to this path for the includes: \sACN\install\include

And library \sACN\install\lib

Also, at the top of my main.cpp:

#pragma comment(lib, "EtcPal.lib")
#pragma comment(lib, "sACN.lib")
It's a 64 bit build I could point out.

The library, and source / receiver examples, build fine with Cmake, I ran both examples without problem.

Do you have any tips if I'm doing something wrong? Or - unlikely - is the install created missing something?

Thanks!

**Comment by ChristianReese** [comment]
Hi @onar3d -

These errors are likely due required Windows library files not being included. Please make sure you're including `ws2_32.lib` and `Iphlpapi.lib` in your project (the latter is likely what's causing the errors you mentioned).

**Comment by ChristianReese** [comment]
`winmm.lib` & `Rpcrt4.lib` will likely be needed as well.

**Comment by onar3d** [comment]
That did the trick!

I can see why you wouldn't include these in a library meant to be statically linked.
What the praxis is for that evades me - I guess listing the names in a README might help?

Thank you for the quick reply!

**Comment by samkearney** [comment]
@onar3d FWIW, the library requirements are listed under "platform dependencies" [here](https://etclabs.github.io/EtcPalDocs/head/) (and that EtcPal docs page is pointed to by the [sACN docs homepage](https://etclabs.github.io/sACNDocs/3.0.0/)

**Comment by onar3d** [comment]
@samkearney Gotcha, thanks again! I wasn't sure that's how it's done so I never looked for it, I've learned something!
